# Clone the git repo.
  #id field to set a unique identifier for a build step.
  # <github_repository> is the name of the gethub repository to be clone
  #args take a list of arguments 
  steps:
  
  # Run tests and save to file
  - name: golang
    entrypoint: /bin/bash
    args: 
      - -c
      - |
        go get -u github.com/jstemmer/go-junit-report
        2>&1 go test -timeout 1m -v ./... | tee sponge.log
        /go/bin/go-junit-report -set-exit-code < sponge.log > ${COMMIT_SHA}_test_log.xml
  # [END cloudbuild_go_test_yaml]
  - name: 'gcr.io/cloud-builders/git'
    id: 'Clone'
    args: ['clone', 'https://github.com/IamPeterPan/cloudbuildingtest-main-check.git']
  
 #builds the container image.
  #build is the entrypoint to the Docker cloud builder
  #-t is the Docker tag
  #<preffered_image_name> is the name of the image to be built
  #. is the location of the source code
  
  - name: 'gcr.io/cloud-builders/docker'
    args:
    - 'build'
    - '-t'
    - 'gcr.io/$PROJECT_ID/$REPO_NAME/cloud-computing-assignment-service/cloud-computing-assignment-service-image:$COMMIT_SHA.0'
    - '.'
  # pushes the image to Container Registry
   # The PROJECT_ID and SHORT_SHA variables are automatically replaced by Cloud Build.
  - name: 'gcr.io/cloud-builders/docker'
    id: Push
    args:
    - 'push'
    - 'gcr.io/$PROJECT_ID/$REPO_NAME/cloud-computing-assignment-service/cloud-computing-assignment-service-image:$COMMIT_SHA.0'
    
    
    # This step deploys the new version of our container image
  # in the hello-cloudbuild Kubernetes Engine cluster.
  - name: 'gcr.io/cloud-builders/kubectl'
    id: Deploy
    args:
    - 'gcloud container clusters get-credentials $CLOUDSDK_CONTAINER_CLUSTER' 
    
    #--zone $CLOUDSDK_COMPUTE_REGION-a'
    - 'apply'
    - '-f'
    - '/manifest/kube-b.yml'
    
    
    env:
    - 'CLOUDSDK_COMPUTE_REGION=us-central1'
    - 'CLOUDSDK_CONTAINER_CLUSTER=cloud-computing-assignment'
#    - name: 'gcr.io/cloud-builders/kubectl'
#     id: Destroy
#     args:
#     - 'delete'
#     - '-f'
#     - '/manifest/kube-b.yml'
#     env:
#     - 'CLOUDSDK_COMPUTE_REGION=us-central1'
#     - 'CLOUDSDK_CONTAINER_CLUSTER=cloud-computing-assignment'
#   # [END cloudbuild_go_yaml]

# Store images in Google Artifact Registry
images:
  - gcr.io/$PROJECT_ID/$REPO_NAME/cloud-computing-assignment-service/cloud-computing-assignment-service-image:$COMMIT_SHA.0
  
  
  

