apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloud-computing-assignment-v2
spec:
  replicas: 3
  selector:
    matchLabels:
      app: cloud-computing-assignment
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      labels:
        app: cloud-computing-assignment
        version: "v2"
    spec:
      containers:
        - name: cloud-computing-assignment
          image: 'us-central1-docker.pkg.dev/cloud-computing-project-2022/cloudbuildingtest-main-check/cloud-computing-assignment-service/cloud-computing-assignment-service-image:v1'
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /lazy
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: cloud-computing-assignment-green
  labels:
    name: cloud-computing-assignment
    version: "v2"
spec:
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: cloud-computing-assignment
    version: "v2"
  type: LoadBalancer
