apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloud-computing-assignment-v1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: cloud-computing-assignment
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      labels:
        app: cloud-computing-assignment
        version: "v1"
    spec:
      containers:
        - name: dataazmolk-sha256-1
          image: 'us-central1-docker.pkg.dev/cloud-computing-project-2022/cloudbuildingtest-main-check/dataazmolk@sha256:fafaa08c1c48bf203ee4cb951caa83c5d116113672f35177857d0ba66cef34d0:v1'
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /lazy
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: cloud-computing-assignment
  labels:
    name: cloud-computing-assignment
    version: "v1"
spec:
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: cloud-computing-assignment
    version: "v1"
  type: LoadBalancer
